---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-fortytwo-deployment
  namespace: fortytwo
  labels:
    app: fortytwo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortytwo
  template:
    metadata:
      labels:
        app: fortytwo
    spec:
      containers:
      - name: web-server
        image: mvpstudio/fortytwo:6e48faee
        resources:
           limits:
              cpu: 0.25
              memory: 250Mi
           requests:
              cpu: 0.25
              memory: 250Mi
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1 
---
apiVersion: v1
kind: Service
metadata:
  name: fortytwo-web
  namespace: fortytwo
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: fortytwo-mapping
      host: 42.stage.apps.mvpstudio.org
      prefix: /
      service: fortytwo-web.fortytwo
      ---
      apiVersion: ambassador/v0
      kind: TLSContext
      name: stage-fortytwo-tls
      hosts:
      - 42.stage.apps.mvpstudio.org
      secret: stage-apps-cert
spec:
  selector:
     app: fortytwo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80